[package]
name = "ex"
version = "0.1.0"
edition = "2023_11"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[[target.starknet-contract]]
allowed-libfuncs-list.name = "audited"
sierra = true
casm = true
casm-add-pythonic-hints = true

[dependencies]
starknet = ">=2.2.0"
